CREATE TYPE VOTACAO_T AS OBJECT (
  partido VARCHAR2(10),
  votos   NUMBER(10)
);

CREATE TYPE VOTACAO_TABLE AS TABLE OF VOTACAO_T;

CREATE TYPE FREGUESIA_T AS OBJECT (
  codigo   NUMBER(6),
  nome     VARCHAR2(50),
  votacoes VOTACAO_TABLE
);

CREATE TYPE FREGUESIA_TABLE AS TABLE OF FREGUESIA_T;

CREATE TYPE CONCELHO_T AS OBJECT (
  codigo     NUMBER(4),
  nome       VARCHAR2(50),
  freguesias FREGUESIA_TABLE
);

CREATE TYPE CONCELHO_TABLE AS TABLE OF CONCELHO_T;

CREATE TYPE PARTICIPACAO_T AS OBJECT (
  inscritos  NUMBER(10),
  votantes   NUMBER(10),
  abstencoes NUMBER(10),
  brancos    NUMBER(10),
  nulos      NUMBER(10)
);

CREATE TYPE PARTICIPACAO_TABLE AS TABLE OF PARTICIPACAO_T;

CREATE TYPE LISTA_T AS OBJECT (
  partido  VARCHAR2(10),
  mandatos NUMBER(2)
);

CREATE TYPE LISTA_TABLE AS TABLE OF LISTA_T;

CREATE TYPE DISTRITO_T AS OBJECT (
  codigo        NUMBER(2),
  nome          VARCHAR2(50),
  regiao        VARCHAR(1),
  concelhos     CONCELHO_TABLE,
  participacoes PARTICIPACAO_TABLE,
  listas        LISTA_TABLE
);

CREATE TYPE DISTRITO_TABLE AS TABLE OF DISTRITO_T;

CREATE TYPE PARTIDO_T AS OBJECT (
  sigla      VARCHAR2(10),
  designacao VARCHAR2(100)
);

CREATE TYPE PARTIDO_TABLE AS TABLE OF PARTIDO_T;

CREATE TYPE ELEICAO_T AS OBJECT (
  distritos DISTRITO_TABLE,
  partidos  PARTIDO_TABLE
);