-- If we considered that there was a
-- AFTER DELETE OR INSERT OR UPDATE trigger
-- ON RESPOSTAS that updated TOTAL_RESPOSTAS
-- x
SELECT s.TOTAL_RESPOSTAS
FROM XSEMESTRE s
WHERE s.SEMESTRE_ID = 21;

-- y
SELECT s.TOTAL_RESPOSTAS
FROM YSEMESTRE s
WHERE s.SEMESTRE_ID = 21;

-- z
SELECT s.TOTAL_RESPOSTAS
FROM ZSEMESTRE s
WHERE s.SEMESTRE_ID = 21;


-- In case there is no trigger for TOTAL_RESPOSTAS
-- x
SELECT count(*)
FROM XRESPOSTAS r
WHERE r.SEMESTRE_ID = 21;

-- y
SELECT count(*)
FROM YRESPOSTAS r
WHERE r.SEMESTRE_ID = 21;

-- z
SELECT count(*)
FROM ZRESPOSTAS r
WHERE r.SEMESTRE_ID = 21;