-- If we considered that there was a
-- AFTER DELETE OR INSERT OR UPDATE trigger
-- ON RESPOSTAS that updated TOTAL_RESPOSTAS
SELECT TOTAL_RESPOSTAS
FROM XSEMESTRE xs
WHERE xs.SEMESTRE_ID = 21;

SELECT TOTAL_RESPOSTAS
FROM YSEMESTRE ys
WHERE ys.SEMESTRE_ID = 21;

SELECT TOTAL_RESPOSTAS
FROM ZSEMESTRE zs
WHERE zs.SEMESTRE_ID = 21;

-- In case there is no trigger for TOTAL_RESPOSTAS
SELECT count(*)
FROM XRESPOSTAS xr
WHERE xr.SEMESTRE_ID = 21;

SELECT count(*)
FROM YRESPOSTAS yr
WHERE yr.SEMESTRE_ID = 21;

SELECT count(*)
FROM ZRESPOSTAS zr
WHERE zr.SEMESTRE_ID = 21;