-- If we considered that there was a
-- AFTER DELETE OR INSERT OR UPDATE trigger
-- ON RESPOSTAS that updated TOTAL_RESPOSTAS
SELECT s.TOTAL_RESPOSTAS
FROM XSEMESTRE s
WHERE s.SEMESTRE_ID = 21;


SELECT s.TOTAL_RESPOSTAS
FROM YSEMESTRE s
WHERE s.SEMESTRE_ID = 21;


SELECT s.TOTAL_RESPOSTAS
FROM ZSEMESTRE s
WHERE s.SEMESTRE_ID = 21;



-- In case there is no trigger for TOTAL_RESPOSTAS
SELECT count(*)
FROM XRESPOSTAS r
WHERE r.SEMESTRE_ID = 21;


SELECT count(*)
FROM YRESPOSTAS r
WHERE r.SEMESTRE_ID = 21;


SELECT count(*)
FROM ZRESPOSTAS r
WHERE r.SEMESTRE_ID = 21;