-- x
SELECT count(*)
FROM XRESPOSTAS r
WHERE r.DISCIPLINA_ID = 1237;

-- y
SELECT count(*)
FROM YRESPOSTAS r
WHERE r.DISCIPLINA_ID = 1237;

-- z
SELECT count(*)
FROM ZRESPOSTAS r
WHERE r.DISCIPLINA_ID = 1237;