-- If we considered that there was a
-- AFTER DELETE OR INSERT OR UPDATE trigger
-- ON RESPOSTAS that updated TOTAL_RESPOSTAS
SELECT SUM(zs.TOTAL_RESPOSTAS)
FROM XSEMESTRE xs
WHERE xs.ANO_LECTIVO = '2008/2009' AND xs.SEMESTRE = '1S';

SELECT SUM(zs.TOTAL_RESPOSTAS)
FROM YSEMESTRE ys
WHERE ys.ANO_LECTIVO = '2008/2009' AND ys.SEMESTRE = '1S';

SELECT SUM(zs.TOTAL_RESPOSTAS)
FROM ZSEMESTRE zs
WHERE zs.ANO_LECTIVO = '2008/2009' AND zs.SEMESTRE = '1S';

-- In case there is no trigger for TOTAL_RESPOSTAS
SELECT count(*)
FROM XRESPOSTAS xr
  INNER JOIN
  (
    SELECT xs.SEMESTRE_ID
    FROM XSEMESTRE xs
    WHERE xs.ANO_LECTIVO = '2008/2009' AND xs.SEMESTRE = '1S'
  ) xs ON xs.SEMESTRE_ID = xr.SEMESTRE_ID;

SELECT count(*)
FROM YRESPOSTAS yr
  INNER JOIN
  (
    SELECT ys.SEMESTRE_ID
    FROM YSEMESTRE ys
    WHERE ys.ANO_LECTIVO = '2008/2009' AND ys.SEMESTRE = '1S'
  ) ys ON ys.SEMESTRE_ID = yr.SEMESTRE_ID;

SELECT count(*)
FROM ZRESPOSTAS zr
  INNER JOIN
  (
    SELECT zs.SEMESTRE_ID
    FROM ZSEMESTRE zs
    WHERE zs.ANO_LECTIVO = '2008/2009' AND zs.SEMESTRE = '1S'
  ) zs ON zs.SEMESTRE_ID = zr.SEMESTRE_ID;

