-- If we considered that there was a
-- AFTER DELETE OR INSERT OR UPDATE trigger
-- ON RESPOSTAS that updated TOTAL_RESPOSTAS
SELECT SUM(s.TOTAL_RESPOSTAS)
FROM XSEMESTRE s
WHERE s.ANO_LECTIVO = '2008/2009' AND s.SEMESTRE = '1S';

SELECT SUM(s.TOTAL_RESPOSTAS)
FROM YSEMESTRE s
WHERE s.ANO_LECTIVO = '2008/2009' AND s.SEMESTRE = '1S';

SELECT SUM(s.TOTAL_RESPOSTAS)
FROM ZSEMESTRE s
WHERE s.ANO_LECTIVO = '2008/2009' AND s.SEMESTRE = '1S';

-- In case there is no trigger for TOTAL_RESPOSTAS
SELECT count(*)
FROM XRESPOSTAS r
WHERE r.SEMESTRE_ID IN (
  SELECT s.SEMESTRE_ID
  FROM XSEMESTRE s
  WHERE s.ANO_LECTIVO = '2008/2009' AND s.SEMESTRE = '1S');

SELECT count(*)
FROM YRESPOSTAS r
WHERE r.SEMESTRE_ID IN (
  SELECT s.SEMESTRE_ID
  FROM YSEMESTRE s
  WHERE s.ANO_LECTIVO = '2008/2009' AND s.SEMESTRE = '1S');

SELECT count(*)
FROM ZRESPOSTAS r
WHERE r.SEMESTRE_ID IN (
  SELECT s.SEMESTRE_ID
  FROM ZSEMESTRE s
  WHERE s.ANO_LECTIVO = '2008/2009' AND s.SEMESTRE = '1S');

