SELECT AVG(r.RESPOSTA)
FROM XRESPOSTAS r
WHERE r.DISCIPLINA_ID = (
  SELECT d.DISCIPLINA_ID
  FROM XDISCIPLINA d
  WHERE d.SIGLA = 'FPRO');


SELECT AVG(r.RESPOSTA)
FROM YRESPOSTAS r
WHERE r.DISCIPLINA_ID = (
  SELECT d.DISCIPLINA_ID
  FROM YDISCIPLINA d
  WHERE d.SIGLA = 'FPRO');


SELECT AVG(r.RESPOSTA)
FROM ZRESPOSTAS r
WHERE r.DISCIPLINA_ID = (
  SELECT d.DISCIPLINA_ID
  FROM ZDISCIPLINA d
  WHERE d.SIGLA = 'FPRO');