-- x
CREATE OR REPLACE VIEW XV_D_R_AVG_G300_DESC AS (
  SELECT
    d.DISCIPLINA_ID,
    d.SIGLA,
    COUNT(r.RESPOSTA) AS N_RESPOSTAS,
    AVG(r.RESPOSTA)   AS AVG_RESPOSTA
  FROM XRESPOSTAS r
    INNER JOIN XDISCIPLINA d ON d.DISCIPLINA_ID = r.DISCIPLINA_ID
  WHERE r.SEMESTRE_ID = 21
  GROUP BY d.DISCIPLINA_ID, d.SIGLA
  HAVING COUNT(r.RESPOSTA) > 300)
  ORDER BY AVG_RESPOSTA DESC;

SELECT
  v.DISCIPLINA_ID,
  v.SIGLA
FROM XV_D_R_AVG_G300_DESC v
FETCH FIRST ROW ONLY;

-- y
CREATE OR REPLACE VIEW YV_D_R_AVG_G300_DESC AS (
  SELECT
    d.DISCIPLINA_ID,
    d.SIGLA,
    COUNT(r.RESPOSTA) AS N_RESPOSTAS,
    AVG(r.RESPOSTA)   AS AVG_RESPOSTA
  FROM YRESPOSTAS r
    INNER JOIN YDISCIPLINA d ON d.DISCIPLINA_ID = r.DISCIPLINA_ID
  WHERE r.SEMESTRE_ID = 21
  GROUP BY d.DISCIPLINA_ID, d.SIGLA
  HAVING COUNT(r.RESPOSTA) > 300)
  ORDER BY AVG_RESPOSTA DESC;

SELECT
  v.DISCIPLINA_ID,
  v.SIGLA
FROM YV_D_R_AVG_G300_DESC v
FETCH FIRST ROW ONLY;

-- z
CREATE OR REPLACE VIEW ZV_D_R_AVG_G300_DESC AS (
  SELECT
    d.DISCIPLINA_ID,
    d.SIGLA,
    COUNT(r.RESPOSTA) AS N_RESPOSTAS,
    AVG(r.RESPOSTA)   AS AVG_RESPOSTA
  FROM ZRESPOSTAS r
    INNER JOIN ZDISCIPLINA d ON d.DISCIPLINA_ID = r.DISCIPLINA_ID
  WHERE r.SEMESTRE_ID = 21
  GROUP BY d.DISCIPLINA_ID, d.SIGLA
  HAVING COUNT(r.RESPOSTA) > 300)
  ORDER BY AVG_RESPOSTA DESC;

SELECT
  v.DISCIPLINA_ID,
  v.SIGLA
FROM ZV_D_R_AVG_G300_DESC v
FETCH FIRST ROW ONLY;