CREATE OR REPLACE VIEW XV_D_R_AVG_G300 AS (
  SELECT
    ro.DISCIPLINA_ID,
    AVG(ro.RESPOSTA) AS AVG_RESPOSTA
  FROM XRESPOSTAS ro
  WHERE ro.DISCIPLINA_ID IN (
    SELECT r.DISCIPLINA_ID
    FROM XRESPOSTAS r
    WHERE r.SEMESTRE_ID = 21
    GROUP BY r.DISCIPLINA_ID
    HAVING COUNT(r.RESPOSTA) > 300
  )
  GROUP BY ro.DISCIPLINA_ID);

SELECT
  d.DISCIPLINA_ID,
  d.SIGLA
FROM XDISCIPLINA d
WHERE d.DISCIPLINA_ID = (
  SELECT v.DISCIPLINA_ID
  FROM XV_D_R_AVG_G300 v
  WHERE v.AVG_RESPOSTA = (
    SELECT MAX(AVG_RESPOSTA)
    FROM XV_D_R_AVG_G300));

CREATE OR REPLACE VIEW YV_D_R_AVG_G300 AS (
  SELECT
    ro.DISCIPLINA_ID,
    AVG(ro.RESPOSTA) AS AVG_RESPOSTA
  FROM YRESPOSTAS ro
  WHERE ro.DISCIPLINA_ID IN (
    SELECT r.DISCIPLINA_ID
    FROM YRESPOSTAS r
    WHERE r.SEMESTRE_ID = 21
    GROUP BY r.DISCIPLINA_ID
    HAVING COUNT(r.RESPOSTA) > 300
  )
  GROUP BY ro.DISCIPLINA_ID);

SELECT
  d.DISCIPLINA_ID,
  d.SIGLA
FROM YDISCIPLINA d
WHERE d.DISCIPLINA_ID = (
  SELECT v.DISCIPLINA_ID
  FROM YV_D_R_AVG_G300 v
  WHERE v.AVG_RESPOSTA = (
    SELECT MAX(AVG_RESPOSTA)
    FROM YV_D_R_AVG_G300));

CREATE OR REPLACE VIEW ZV_D_R_AVG_G300 AS (
  SELECT
    ro.DISCIPLINA_ID,
    AVG(ro.RESPOSTA) AS AVG_RESPOSTA
  FROM ZRESPOSTAS ro
  WHERE ro.DISCIPLINA_ID IN (
    SELECT r.DISCIPLINA_ID
    FROM ZRESPOSTAS r
    WHERE r.SEMESTRE_ID = 21
    GROUP BY r.DISCIPLINA_ID
    HAVING COUNT(r.RESPOSTA) > 300
  )
  GROUP BY ro.DISCIPLINA_ID);

SELECT
  d.DISCIPLINA_ID,
  d.SIGLA
FROM ZDISCIPLINA d
WHERE d.DISCIPLINA_ID = (
  SELECT v.DISCIPLINA_ID
  FROM ZV_D_R_AVG_G300 v
  WHERE v.AVG_RESPOSTA = (
    SELECT MAX(AVG_RESPOSTA)
    FROM ZV_D_R_AVG_G300));
