-- x
CREATE OR REPLACE VIEW XV_D_R_AVG_APGL AS (
  SELECT
    r.DISCIPLINA_ID,
    AVG(r.RESPOSTA) AS AVG_RESPOSTA
  FROM XRESPOSTAS r
    INNER JOIN XPERGUNTA p ON p.PERGUNTA_ID = r.PERGUNTA_ID AND p.NOME = 'Apreciação Global'
  WHERE r.SEMESTRE_ID = 21
  GROUP BY r.DISCIPLINA_ID);

CREATE OR REPLACE VIEW XV_D_R_AVG_G300 AS (
  SELECT
    r.DISCIPLINA_ID,
    AVG(r.RESPOSTA) AS AVG_RESPOSTA
  FROM XRESPOSTAS r
  WHERE r.SEMESTRE_ID = 21
  GROUP BY r.DISCIPLINA_ID
  HAVING COUNT(r.RESPOSTA) > 300);

SELECT
  d.DISCIPLINA_ID,
  d.SIGLA
FROM XDISCIPLINA d
  INNER JOIN XV_D_R_AVG_APGL apgl ON apgl.DISCIPLINA_ID = d.DISCIPLINA_ID
  INNER JOIN XV_D_R_AVG_G300 g300 ON g300.DISCIPLINA_ID = d.DISCIPLINA_ID
WHERE apgl.AVG_RESPOSTA > g300.AVG_RESPOSTA + 0.1;

-- y
CREATE OR REPLACE VIEW YV_D_R_AVG_APGL AS (
  SELECT
    r.DISCIPLINA_ID,
    AVG(r.RESPOSTA) AS AVG_RESPOSTA
  FROM YRESPOSTAS r
    INNER JOIN YPERGUNTA p ON p.PERGUNTA_ID = r.PERGUNTA_ID AND p.NOME = 'Apreciação Global'
  WHERE r.SEMESTRE_ID = 21
  GROUP BY r.DISCIPLINA_ID);

CREATE OR REPLACE VIEW YV_D_R_AVG_G300 AS (
  SELECT
    r.DISCIPLINA_ID,
    AVG(r.RESPOSTA) AS AVG_RESPOSTA
  FROM YRESPOSTAS r
  WHERE r.SEMESTRE_ID = 21
  GROUP BY r.DISCIPLINA_ID
  HAVING COUNT(r.RESPOSTA) > 300);

SELECT
  d.DISCIPLINA_ID,
  d.SIGLA
FROM YDISCIPLINA d
  INNER JOIN YV_D_R_AVG_APGL apgl ON apgl.DISCIPLINA_ID = d.DISCIPLINA_ID
  INNER JOIN YV_D_R_AVG_G300 g300 ON g300.DISCIPLINA_ID = d.DISCIPLINA_ID
WHERE apgl.AVG_RESPOSTA > g300.AVG_RESPOSTA + 0.1;

-- z
CREATE OR REPLACE VIEW ZV_D_R_AVG_APGL AS (
  SELECT
    r.DISCIPLINA_ID,
    AVG(r.RESPOSTA) AS AVG_RESPOSTA
  FROM ZRESPOSTAS r
    INNER JOIN ZPERGUNTA p ON p.PERGUNTA_ID = r.PERGUNTA_ID AND p.NOME = 'Apreciação Global'
  WHERE r.SEMESTRE_ID = 21
  GROUP BY r.DISCIPLINA_ID);

CREATE OR REPLACE VIEW ZV_D_R_AVG_G300 AS (
  SELECT
    r.DISCIPLINA_ID,
    AVG(r.RESPOSTA) AS AVG_RESPOSTA
  FROM ZRESPOSTAS r
  WHERE r.SEMESTRE_ID = 21
  GROUP BY r.DISCIPLINA_ID
  HAVING COUNT(r.RESPOSTA) > 300);

SELECT
  d.DISCIPLINA_ID,
  d.SIGLA
FROM ZDISCIPLINA d
  INNER JOIN ZV_D_R_AVG_APGL apgl ON apgl.DISCIPLINA_ID = d.DISCIPLINA_ID
  INNER JOIN ZV_D_R_AVG_G300 g300 ON g300.DISCIPLINA_ID = d.DISCIPLINA_ID
WHERE apgl.AVG_RESPOSTA > g300.AVG_RESPOSTA + 0.1;