CREATE OR REPLACE VIEW XV_D_R_AVG_G300 AS (
  SELECT
    ro.DISCIPLINA_ID,
    AVG(ro.RESPOSTA) AS AVG_RESPOSTA
  FROM XRESPOSTAS ro
  WHERE ro.DISCIPLINA_ID IN (
    SELECT r.DISCIPLINA_ID
    FROM XRESPOSTAS r
    WHERE r.SEMESTRE_ID = 21
    GROUP BY r.DISCIPLINA_ID
    HAVING COUNT(r.RESPOSTA) > 300
  )
  GROUP BY ro.DISCIPLINA_ID);